name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    # Skip build if head commit contains 'skip ci'
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'true'

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - uses: gradle/gradle-build-action@v2

      - name: Build samples
        run: |
          ./gradlew :sample:android:assemble